-- Para comparação das tabelas de grupos de estruturas

SELECT
    "GROUP"."ID" AS "STRUCTURE_GROUP_ID", 
    "GROUP"."TITLE" AS "STRUCTURE_GROUP_NAME",
    "GROUP"."CREATION.ID_USER" AS "CREATION_USER_ID",
    "GROUP"."MODIFICATION.ID_USER" AS "MODIFICATION_USER_ID",
    "CREATION.USER"."HANA_USER" AS "CREATION_USER",
    "MODIFICATION.USER"."HANA_USER" AS "MODIFICATION_USER",
    "GROUP"."CREATION.DATE" AS "CREATION_DATE",
    "GROUP"."MODIFICATION.DATE" AS "MODIFICATION_DATE"
FROM "AP_TIMP"."ATR::StructureGroup" AS "GROUP"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "CREATION.USER" ON
    "CREATION.USER"."ID" = "GROUP"."CREATION.ID_USER"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "MODIFICATION.USER" ON
    "MODIFICATION.USER"."ID" = "GROUP"."MODIFICATION.ID_USER"
ORDER BY "GROUP"."ID";

SELECT
    "GROUP"."STRUCTURE_GROUP_ID", 
    "STRUCT_GROUP"."TITLE" AS "STRUCTURE_GROUP_NAME",
    "GROUP"."STRUCTURE_ID", 
    "STRUCT"."title" AS "STRUCTURE_NAME"
FROM "AP_TIMP"."ATR::StructureGroupXStructure" AS "GROUP"
INNER JOIN "AP_TIMP"."ATR::StructureGroup" AS "STRUCT_GROUP" ON
    "STRUCT_GROUP"."ID" = "GROUP"."STRUCTURE_GROUP_ID"
INNER JOIN "AP_TIMP"."ATR::Structure" AS "STRUCT" ON
    "STRUCT"."ID" = "GROUP"."STRUCTURE_ID"
ORDER BY "GROUP"."STRUCTURE_GROUP_ID", "GROUP"."STRUCTURE_ID";

-- Para comparação das tabelas de mapeamentos de groupos de estruturas

SELECT
    "MAPPING"."ID" AS "MAPPING_ID", 
    "MAPPING"."STRUCTURE_ID", 
    "STRUCT"."title" AS "STRUCTURE_NAME", 
    "MAPPING"."EMPRESA", 
    "MAPPING"."UF_FILIAL", 
    "MAPPING"."FILIAL", 
    "MAPPING"."DATA", 
    "MAPPING"."DATA2",
    "MAPPING"."MAPPING", 
    "MAPPING"."UF_ST", 
    "MAPPING"."DATE_FORMAT",
    "MAPPING"."CREATION.ID_USER" AS "CREATION_USER_ID",
    "MAPPING"."MODIFICATION.ID_USER" AS "MODIFICATION_USER_ID",
    "CREATION.USER"."HANA_USER" AS "CREATION_USER",
    "MODIFICATION.USER"."HANA_USER" AS "MODIFICATION_USER",
    "MAPPING"."CREATION.DATE" AS "CREATION_DATE",
    "MAPPING"."MODIFICATION.DATE" AS "MODIFICATION_DATE"
FROM "AP_TIMP"."ATR::StructureFieldMapping" AS "MAPPING"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "CREATION.USER" ON
    "CREATION.USER"."ID" = "MAPPING"."CREATION.ID_USER"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "MODIFICATION.USER" ON
    "MODIFICATION.USER"."ID" = "MAPPING"."MODIFICATION.ID_USER"
INNER JOIN "AP_TIMP"."ATR::Structure" AS "STRUCT" ON
    "STRUCT"."ID" = "MAPPING"."STRUCTURE_ID"
ORDER BY "MAPPING"."STRUCTURE_ID", "MAPPING"."ID";

SELECT
    "MAPPING"."STRUCTURE_ID",
    "MAPPING"."ID" AS "MAPPING_ID", 
    "STRUCT"."title" AS "STRUCTURE_NAME",
    "MAPPING_TRIBUTO"."COD_TRIBUTO", 
    "TRIBUTO"."DESCR_COD_TRIBUTO_LABEL" AS "TAX_NAME"
FROM "AP_TIMP"."ATR::StructureFieldMappingXTributo" AS "MAPPING_TRIBUTO"
INNER JOIN "AP_TIMP"."ATR::Tributo" AS "TRIBUTO" ON
    "TRIBUTO"."COD_TRIBUTO" = "MAPPING_TRIBUTO"."COD_TRIBUTO"
INNER JOIN "AP_TIMP"."ATR::StructureFieldMapping" AS "MAPPING" ON
    "MAPPING"."ID" = "MAPPING_TRIBUTO"."STRUCTURE_FIELD_MAPPING_ID"
INNER JOIN "AP_TIMP"."ATR::Structure" AS "STRUCT" ON
    "STRUCT"."ID" = "MAPPING"."STRUCTURE_ID"
ORDER BY "STRUCT"."ID", "MAPPING"."ID", "MAPPING_TRIBUTO"."COD_TRIBUTO";

-- Para comparação das tabelas de mapeamento de parâmetros de entrada

SELECT 
    "MAPPING"."ID" AS "MAPPING_ID",
    "MAPPING"."STRUCTURE_ID",
    "MAPPING"."STRUCTURE_NAME",
    "MAPPING"."CREATION_USER" AS "CREATION_USER_ID",
    "MAPPING"."MODIFICATION_USER" AS "MODIFICATION_USER_ID",
    "CREATION.USER"."HANA_USER" AS "CREATION_USER",
    "MODIFICATION.USER"."HANA_USER" AS "MODIFICATION_USER",
    "MAPPING"."CREATION_DATE",
    "MAPPING"."MODIFICATION_DATE"
FROM "AP_TIMP"."ATR::INPUT_PARAMETERS_MAPPING" AS "MAPPING"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "CREATION.USER" ON
    "CREATION.USER"."ID" = "MAPPING"."CREATION_USER"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "MODIFICATION.USER" ON
    "MODIFICATION.USER"."ID" = "MAPPING"."MODIFICATION_USER"
ORDER BY "MAPPING"."STRUCTURE_ID", "MAPPING"."ID";

SELECT 
    "FIELD"."MAPPING_ID",
    "FIELD"."IS_MANUAL",
    "FIELD"."VALUE",
    "FIELD"."INPUT_PARAMETER",
    "FIELD"."OPERATOR",
    "FIELD"."DATE_FORMAT"
FROM "AP_TIMP"."ATR::INPUT_PARAMETERS_MAPPING_FIELDS_X_MAPPING" AS "FIELD"
ORDER BY "FIELD"."MAPPING_ID", "FIELD"."INPUT_PARAMETER";

SELECT 
    "MAPPING"."ID" AS "MAPPING_ID",
    "MAPPING"."STRUCTURE_ID",
    "STRUCT"."title" as "STRUCTURE_NAME",
    "MAPPING"."INPUT_PARAMETERS_MAPPING_ID",
    "MAPPING"."TRIBUTO_KEY" AS "COD_TRIBUTO",
    "MAPPING"."TRIBUTO_NAME" AS "DESC_TRIBUTO",
    "MAPPING"."CREATION_USER" AS "CREATION_USER_ID",
    "MAPPING"."MODIFICATION_USER" AS "MODIFICATION_USER_ID",
    "CREATION.USER"."HANA_USER" AS "CREATION_USER",
    "MODIFICATION.USER"."HANA_USER" AS "MODIFICATION_USER",
    "MAPPING"."CREATION_DATE",
    "MAPPING"."MODIFICATION_DATE"
FROM "AP_TIMP"."ATR::INPUT_PARAMETERS_MAPPING_AUX" AS "MAPPING"
INNER JOIN "AP_TIMP"."ATR::Structure" AS "STRUCT" ON
    "STRUCT"."ID" = "MAPPING"."STRUCTURE_ID"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "CREATION.USER" ON
    "CREATION.USER"."ID" = "MAPPING"."CREATION_USER"
LEFT OUTER JOIN "AP_TIMP"."CORE::USER" AS "MODIFICATION.USER" ON
    "MODIFICATION.USER"."ID" = "MAPPING"."MODIFICATION_USER"
ORDER BY "MAPPING"."STRUCTURE_ID", "MAPPING"."ID";